name: GitHub Pages Traffic Badge

on:
  push:
    branches:
      - main # IMPORTANT: Make sure this is your default branch (usually 'main' or 'master')
  workflow_dispatch: # This allows you to manually run the action from the Actions tab
  schedule:
    - cron: '0 * * * *' # This will run the action every hour on the hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Traffic Badge
        uses: gayanvoice/insights@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ github.repository }} # This automatically gets your repo name (charmsmods/Charms-Main-Site)
          output_path: './traffic.svg' # The counter image will be saved as traffic.svg in the root of your repo
      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add traffic.svg
          git commit -m "Update traffic badge" || echo "No changes to commit"
          git push
